DemoMVC/Models/ErrorViewModel.cs
namespace DemoMVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

DemoMVC/Models/PTbac2.cs
public class PTbac2 {
    public double a { get; set; }
    public double b { get; set; }
    public double c { get; set; }
    public double delta { get; set; }
    public double x1 { get; set; }
    public double x2 { get; set; } 
}

DemoMVC/Models/Person.cs
namespace DemoMVC.Models.Person;
public class Person
{
    public string PersonID { get; set; }
    public string FullName { get; set; }
    
}

DemoMVC/Models/Student.cs
using System;
namespace DemoMVC.Models;

public class Student
{
    public int StudentID { get; set; }
    public  string FullName { get; set; }
}

DemoMVC/Controllers/DemoController.cs
using Microsoft.AspNetCore.Mvc;

namespace DemoMVC.Controllers
{
    public class DemoController : Controller
    {
        //khai bao cac phuong thuc
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(string fName, string Email)
        {
            string strResult = "Hello " + fName + "-" + Email;
            ViewBag.thongBao = strResult;
            return View();
            
        }

    }
}

DemoMVC/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;

public class EmployeeController : Controller 
{
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Index(string hoTen, decimal luongCoBan, decimal heSoLuong, decimal phuCap)
    {
        decimal luong = luongCoBan + heSoLuong + phuCap;
        string tinhLuong = hoTen + "-" + luong;
        ViewBag.thongBao = tinhLuong;
        return View();
    }
}

DemoMVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using DemoMVC.Models;

namespace DemoMVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Index(string Fullname, string Address)
    {
        string strOutput = "Xin chào" + Fullname + "Đến từ" + Address;
        ViewBag.Message = strOutput;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    public IActionResult Demo()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

DemoMVC/Controllers/PTbac2Controller.cs
using Microsoft.AspNetCore.Mvc;

public class PTbac2Controller : Controller 
{
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Index(PTbac2 model){
        double delta = model.b * model.b - 4 * model.a *model.c;
        if(delta<0)
        {
            ViewData["Result"] = "Phuong Trinh vo nghiem";
        }
        else if(delta ==0)
        {
            model.x1 = -model.b / (2*model.a);
            ViewData["Result"] = "Phuong trinh co nghiem kep:" + model.x1;
        }
        else
        {
            model.x1 =(-model.b + Math.Sqrt(delta)) / (2*model.a);
            model.x2 = (-model.b - Math.Sqrt(delta)) / (2*model.a);
            ViewData["Result"] = "Phuong trinh co 2 nghiem: x1 =" +model.x1 + ", x2 = " +model.x2;
        }
        return View();
    }
}

DemoMVC/Controllers/PersonController.cs
using DemoMVC.Controllers;
using DemoMVC.Models.Person;
using Microsoft.AspNetCore.Mvc;

public class PersonController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Index(Person ps)
    {
        string strResult = ps.PersonID + "-" + ps.FullName;
        ViewBag.thongBao = strResult;    
        return View();
    }
}

DemoMVC/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;

namespace DemoMVC.Controllers;

public class StudentController  :   Controller

{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Index(string StudentID, string FullName)
    {
        string strResult = "Hello " + StudentID + "-" + FullName;
        ViewBag.thongBao = strResult;
        return View();
    }
}

DemoMVC/Views/Demo/Index.cshtml
<form asp-action="Index">
    <><Label>Fullname:</Label>
    <input type="text" name="fName" placeholder="Enter fullname ">
    <input type="email" name="Email" placeholder="Enter Email">
    <input type="submit" value="Save"/>
</form>
<h1>@ViewBag.thongBao</h1>

DemoMVC/Views/Employee/Index.cshtml
 <h2>Nhap thong tin nhan vien:</h2>
    <form asp-action="Index">
        Ho ten: <input type="text" name="hoTen" placeholder="HoTen">
        Luong co ban: <input type="text" name="luongCoBan" placeholder="LuongCoBan">
        He so luong: <input type="text" name="heSoLuong" placeholder="HeSoLuong">
        Phu cap: <input type="text" name="phuCap" placeholder="PhuCap">
        <input type="submit" name="Tinh" id="Tinh">


    </form>
<h1>@ViewBag.thongBao</h1>

DemoMVC/Views/Home/Demo.cshtml
Demo 

DemoMVC/Views/PTbac2/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PTbac2</title>
</head>
<body>
    <h1>Giai phuong trinh bac 2:</h1>
    @model PTbac2
    <form asp-action="IndexPTbac2">
        a : <input type="text" name="a" placeholder="a">
        b : <input type="text" name="b" placeholder="b">
        c : <input type="text" name="c" placeholder="c">
        <input type="submit" name="Bang" value="Bang">
    </form>
    @if(ViewData["Result"] != null  )
    {
        <div>
            <p>@ViewData["Result"]</p>
        </div>
    }
</body>
</html>

DemoMVC/Views/Person/Index.cshtml
<form asp-action="Index">
    <label>Person :</label>
    <input type="text" name="PersonID" placeholder="Enter ID"/>
    <input type="text" name="FullName" placeholder="Enter Full Name" />
    <input type="submit" value="Save"/>
</form>
<h1>@ViewBag.thongBao</h1>

DemoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Demo" asp-action="Index">Index</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - DemoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DemoMVC/Views/Student/Index.cshtml
<form asp-action="Index">
    <label>Student:</label>
    <input type="text" name="StudentID" placeholder="Enter ID"/>
    <input type="text" name="FullName" placeholder="Enter Full Name" />
    <input type="submit" value="Save"/>
</form>
<h1>@ViewBag.thongBao</h1>